@startuml
title 4.1 登録内容更新
hide footbox

actor "user A" as user_a
participant "モバイル A" as mobile_a
database "UserDefault A" as user_default_a
database "Realm A" as realm_a
participant "MeiyuAPI" as meiyu_api
database "MySQL" as mysql

activate user_a
user_a -> mobile_a : 登録内容更新

activate mobile_a
mobile_a -> meiyu_api : 登録内容更新

activate meiyu_api
meiyu_api -> mysql : 登録内容更新

activate mysql
mysql -> meiyu_api : 更新後内容

deactivate mysql

meiyu_api -> mobile_a : 更新後内容

deactivate meiyu_api

mobile_a -> user_default_a : 更新後内容

activate user_default_a
user_default_a -> mobile_a : ok

deactivate user_default_a

mobile_a -> user_a : 更新完了

deactivate mobile_a
deactivate user_a

@enduml