@startuml
title 3.1 meiyu申請
hide footbox

actor "user A" as user_a
participant "モバイル A" as mobile_a
database "UserDefault A" as user_default_a
database "Realm A" as realm_a
participant "MeiyuAPI" as meiyu_api
database "MySQL" as mysql
participant "モバイル B" as mobile_b
database "UserDefault B" as user_default_b
database "Realm B" as realm_b
actor "user B" as user_b


activate user_a
user_a -> mobile_a : user Bへのmeiyu申請

activate mobile_a
mobile_a -> realm_a : AのRealmに申請情報を保存

activate realm_a
realm_a -> mobile_a : ok
deactivate realm_a

mobile_a -> meiyu_api : MySQLに申請情報を登録

activate meiyu_api
meiyu_api -> mysql : 登録

activate mysql
mysql -> meiyu_api : ok
deactivate mysql

meiyu_api -> mobile_b : 申請通知（プッシュ通知）
activate mobile_b

meiyu_api -> mobile_a : ok

deactivate meiyu_api

mobile_a -> user_a : 申請完了通知
deactivate mobile_a
deactivate user_a

mobile_b -> meiyu_api : 申請情報取得

activate meiyu_api
meiyu_api -> mysql : 申請情報取得

activate mysql
mysql -> meiyu_api : 申請情報
deactivate mysql

meiyu_api -> mobile_b : 申請情報
deactivate meiyu_api

mobile_b -> realm_b : 申請情報同期

activate realm_b
realm_b -> mobile_b : ok
deactivate realm_b

mobile_b -> user_b : 申請通知（to 3.2, 3.3）
deactivate mobile_b


@enduml