# default: &default
#   adapter: mysql2
#   encoding: utf8
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: root
#   password:
#   host: localhost

default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 1Akadaruma # docker-compose.ymlのMYSQL_ROOT_PASSWORD
  host: db # docker-compose.ymlのservice名

development:
  <<: *default
  database: meiyu_api_development

test:
  <<: *default
  database: meiyu_api_test

production:
  <<: *default
  database: meiyu_api_production
  username: meiyu_api
  password: <%= ENV['MEIYU_API_DATABASE_PASSWORD'] %>
